### ISSUE TITLE
Resumo de Sistemas Distribuídos 

### ISSUE THREAD

**Issue by Eojotap** [Prof-Calebe/livro-sistemas-distribuidos#10]
# Arquitetura e Modelos de Sistemas Distribuídos

### Sistemas Centralizados
- A lógica é dividida entre cliente e servidor.
- A comunicação é centralizada, geralmente com um único servidor gerenciando as solicitações dos clientes.

### Sistemas Distribuídos
- A arquitetura é geograficamente dividida.
- Os componentes comunicam-se através de uma rede, oferecendo maior flexibilidade e escalabilidade.

### Arquitetura
- Foco na diminuição das partes lógicas até alcançar a distribuição desejada.
- Determina como os componentes se comunicam e colaboram.

### Modelos
- Estudados separadamente, sem uma divisão lógica pré-definida.
- A implantação dos modelos é crucial para o desenvolvimento eficiente.

### Clientes
- Podem ser projetados para serem terminais "finos" ou "grossos".
- Iniciam solicitações e consomem serviços fornecidos pelos servidores.

### Servidores
- Fornecem os serviços necessários para os clientes.
- Processam solicitações e retornam respostas.

### Microsserviços
- Parte da arquitetura que divide a aplicação em pequenos serviços independentes.
- Cada serviço é responsável por uma funcionalidade específica, facilitando manutenção e escalabilidade.

### Operacional
- Envolve o uso de termodinâmica de forma diferente para otimizar processos.

### Executor
- Grupos que viajam e utilizam observações para melhorar a eficiência.

### Federação
- Entidades que colaboram no contexto de sistemas distribuídos.

### Percepção
- Necessária para ajustar a máquina às condições de operação.

### Pulmão
- Metáfora para componentes críticos que devem ser tratados com cuidado.

### Recursos Computacionais
- Necessários para a distribuição eficiente de processos.

### Disciplina
- Importante para manter a integridade do projeto sem sobrecarregá-lo.

### Entrevista
- Processo técnico fundamental para avaliar e refinar o sistema.

### Cultura
- Deve ser híbrida e adaptável às necessidades do sistema.

### Arquitetura Híbrida
- Combina diferentes modelos de arquitetura para aproveitar suas vantagens.
- Deve ser bem trabalhada para demonstrar benefícios claros.

### Arquitetura O-Modelo
- Representa sistemas centralizados e servidores.

### Arquitetura de Referência
- Conjunto de modelos, visões e componentes principais que guiam o design do sistema.

### SOA (Service-Oriented Architecture)
- Arquitetura orientada a serviços.

### Microservices
- Arquitetura de microsserviços, focada em serviços independentes.

### Serverless
- Arquitetura sem servidores gerenciados, utilizando serviços de terceiros.

### Cloud Native
- Arquitetura nativa de nuvem, projetada para ambientes de nuvem.

### DDD (Domain-Driven Design)
- Arquitetura orientada a domínio.

### 12-factor
- Método para desenvolvimento de aplicativos em nuvem.

### Arquitetura Limpa
- Boas práticas para desenvolvimento de software.

### Arquitetura Hexagonal
- Isolamento do domínio do software.

### Arquitetura Layered
- Camadas de responsabilidades claras.

### Arquitetura Onion
- Inversão de dependências para maior modularidade.

### Arquitetura ESB (Enterprise Service Bus)
- Integração de sistemas através de um barramento de serviços.

### Arquitetura de Eventos
- Comunicação por meio de eventos.

### Arquitetura de Microfrontends
- Desenvolvimento web em microsserviços.

### AA
- Diferença relacionada à máquina.

### BB
- Diferença não especificada, requer investigação.

### Necessidade em Sistemas Distribuídos
- Mesmo em sistemas distribuídos, modelos centralizados podem ser necessários para garantir certas funcionalidades.

### Impacto no Design
- Modelos centralizados influenciam decisões de design e o funcionamento global do sistema.

### Conceitos Essenciais
- Área de texto, dados e stack são cruciais para a execução de programas.

### Sistemas Operacionais e Threads
- Gestão de processos e threads é fundamental para a eficiência dos sistemas distribuídos.

### Virtualização
- Ajuda a resolver problemas de alocação de recursos em sistemas distribuídos.

### Sincronização
- Essencial para garantir a consistência entre processos.

### Desafios e Soluções
- Manter a sincronia e consistência em ambientes com múltiplos usuários e processos simultâneos.

### Técnicas
- Migração fraca e forte de processos para otimizar a distribuição de carga.

### Importância
- Compreender os conceitos de arquitetura e processos é crucial para o design eficaz de sistemas.

## Conclusão

A complexidade dos sistemas distribuídos requer uma compreensão profunda das arquiteturas centralizadas e distribuídas, processos, virtualização, sincronização e modelos de comunicação. A prática e a experimentação são essenciais para desenvolver soluções eficientes e escaláveis em ambientes distribuídos.

### O que é
Envolve vários computadores interconectados colaborando para executar determinadas tarefas.

### Vantagens
- Escalabilidade
- Disponibilidade
- Tolerância a falhas

### Desvantagens
- Heterogeneidade
- Segurança
- Concorrência
- Complexidade na comunicação

### Cliente-Servidor
Divide as responsabilidades entre clientes ou solicitantes e servidores ou provedores de serviço.

### Multicamadas
Organiza os componentes distribuídos em camadas com diferentes abstrações.

### Peer-to-Peer
Todos os nós no sistema têm a mesma função e podem comunicar entre si diretamente.

### Híbrida
Combina diversos modelos de arquitetura acima citados.

### O que é
Uma instância de um programa em execução que possui um estado próprio.

### Componentes
- Área de texto
- Área de dados
- Área de stack

### Ciclo de Vida
- Criação
- Execução
- Espera
- Pronto
- Término

### Gerenciamento
Inclui escalonamento, sincronização e comunicação entre processos.

### Clientes
Inicia solicitações, composta por interfaces de usuário, envia solicitações para servidores.

### Servidores
Recebe solicitações, fornece serviços, processa operações e retorna resultados.

### Comunicação
Por meio de protocolos de rede HTTP, TCP/IP, UDP, pode ser síncrono ou assíncrono.

### Vantagens
- Escalabilidade
- Desempenho
- Flexibilidade
- Facilidade de manutenção

### Desvantagens
- Rede dependente
- Custo de infraestrutura
- Ponto único de falha
- Latência de rede

### O que é
Todos os nós possuem capacidades equivalentes, sem um servidor central.

### Autonomia
Cada nó é independente, robustez e resiliência aumentadas.

### Arquitetura
Pode ser tanto totalmente descentralizada quanto híbrida.

### Distribuição de Recursos
Equilibrada entre os nós.

### Protocolos
BitTorrent, Gnutella, Kademlia, etc.

### Aplicativos
Incluem compartilhamento de arquivos, comunicação, redes sociais etc.

### Vantagens
- Escalabilidade
- Robustez
- Distribuição de carga

### Limitações
- Gerenciamento de recursos
- Segurança
- Descoberta de pares

### Definição
Padrão de comunicação para sistemas distribuídos, responsável pela comunicação via mensagens entre processos.

### Características
Permite a troca de informações por processos em sistemas distribuídos, muito utilizado em paralelismo de computadores e clusters.

### Funcionamento
As mensagens são enviadas e recebidas de forma assíncrona, podendo ser usadas para coordenar a execução de tarefas em máquinas diferentes.

### Principais Conceitos
- Comunicação ponto a ponto: a troca de mensagens ocorre entre dois processos específicos.
- Comunicação coletiva: a troca de mensagens ocorre entre grupos de processos.

### Vantagens
- Eficiência na troca de informações com processos.
- Mais fácil de implementar algoritmos paralelos e distribuídos.
- Pode ser implementado com outros modelos de programação paralela.

### Desvantagens
- Deve se ter conhecimento e familiaridade do padrão MPI.
- Maior sobrecarga devido a comunicações de grandes distâncias ou volumes de dados.

### Aplicações
- Simulações científicas e computação de alto desempenho.
- Análise distribuída.
- Processamento de grandes volumes de dados com múltiplos computadores em clusters.

### Relógios de Quartzo e Atômicos
- Relógios de quartzo são usados em computadores como base para relógios mantidos em software.
- Relógios atômicos são mais precisos e utilizados em sistemas de sincronização.

### Tempo Universal Coordenado (UTC)
Padrão global para coordenar a medição da passagem do tempo, baseado em relógios atômicos.

### Sincronização de Relógios
É o procedimento de ajustar os relógios em diferentes dispositivos para que eles marquem o mesmo tempo.

### Algoritmos de Sincronização
- Berkeley: um algoritmo em que um nó central consulta outros nós e ajusta o tempo.
- Cristian: um nó cliente solicita a hora de um servidor confiável.
- NTP (Network Time Protocol): protocolo usado para sincronizar os relógios de sistemas de computadores através da rede.

## Referências
- [SOA – Service-Oriented Architecture](https://en.wikipedia.org/wiki/Service-oriented_architecture)
- [Microservices](https://en.wikipedia.org/wiki/Microservices)
- [Serverless](https://en.wikipedia.org/wiki/Serverless_computing)
- [Cloud Native](https://en.wikipedia.org/wiki/Cloud_native_computing)
- [DDD – Domain-Driven Design](https://en.wikipedia.org/wiki/Domain-driven_design)
- [12-Factor App](https://12factor.net/)
- [Clean Architecture](https://en.wikipedia.org/wiki/Clean_architecture)
- [Hexagonal Architecture](https://en.wikipedia.org/wiki/Hexagonal_architecture)
- [Layered Architecture](https://en.wikipedia.org/wiki/Multitier_architecture)
- [Onion Architecture](https://en.wikipedia.org/wiki/Onion_architecture)
- [Enterprise Service Bus (ESB)](https://en.wikipedia.org/wiki/Enterprise_service_bus)
- [Event-Driven Architecture](https://en.wikipedia.org/wiki/Event-driven_architecture)
- [Micro Frontends](https://micro-frontends.org/)
- [MPI – Message Passing Interface](https://en.wikipedia.org/wiki/Message_Passing_Interface)
- [Network Time Protocol (NTP)](https://en.wikipedia.org/wiki/Network_Time_Protocol)

**Comment by calebepb** [comment]
Esses comentários todos devem entrar como PR no repositório, contribuindo efetivamente com o _livro_.
